version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/initial.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static/index.html:/var/www/ean/index.html
